# loki-values.yaml
global:
  defaultStorageClass: "nfs-csi"
  storageClass: "nfs-csi"
  
persistence:
  enabled: true
  storageClass: nfs-csi # local-path # 指定 StorageClass
  accessMode: 
  - ReadWriteOnce
  size: 8Gi

service:
  type: NodePort
  ports:
    api: 9000
    console: 9001
  nodePorts: 
    api: 32000
    console: 32001

# resources:
#   requests:
#     memory: 1Gi