apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init"
  labels:
    {{- include "zadig.init.labels" . | nindent 4 }}
{{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | trimSuffix "\n" | indent 4 }}
{{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
{{- if .Values.additionalAnnotations }}
{{ toYaml .Values.additionalAnnotations | trimSuffix "\n" | indent 4 }}
{{- end }}
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        {{- include "zadig.init.selectorLabels" . | nindent 8 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | trimSuffix "\n" | indent 8 }}
{{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zadig.serviceAccountName" .}}
      restartPolicy: Never
      containers:
        - name: init-job
          image: {{ .Values.global.image.registry }}/{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "Always" }}
          args:
            - "init"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: zadig-aes-key
                  key: aesKey
            - name: BE_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: aslan-config
          volumeMounts:
            - mountPath: /etc/encryption
              name: aes-key
              readOnly: true
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
      volumes:
        - name: aes-key
          secret:
            secretName: zadig-aes-key
            items:
              - key: aesKey
                path: aes
