# ci/alert-values.yaml
loki:
  structuredConfig:
    memberlist:
      join_members:
        - loki-loki-distributed-memberlist
      bind_addr:
        - 0.0.0.0
      advertise_addr: ${POD_IP}
      advertise_port: 7946
    ingester:
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
    storage_config: # 存储的配置，定义其他组件可能用到的存储
      aws: # s3 / s3 兼容的对象存储
        endpoint: minio.logging.svc.cluster.local:9000 # 使用 MiniO API 调用端口
        insecure: true
        bucketnames: loki-data
        # 访问 MiniO 的凭证
        access_key_id: admin # kubectl get secret minio -n logging -o jsonpath='{.data.root-user}' | base64 -d && echo
        secret_access_key: GlE0rh4igD # kubectl get secret minio -n logging -o jsonpath='{.data.root-password}' | base64 -d && echo
        s3forcepathstyle: true
      boltdb_shipper:
        shared_store: s3
    schema_config:
      configs:
        - from: 2022-06-21
          store: boltdb-shipper # index
          object_store: s3 # chunks
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: http://alertmanager-main.monitoring.svc.cluster.local:9093
      external_url: http://192.168.160.35:25772

distributor:
  replicas: 2
  maxUnavailable: 1
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

ingester: # WAL（replay）
  replicas: 2
  maxUnavailable: 1
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  persistence:
    enabled: true
    size: 1Gi
    storageClass: nfs-csi # local-path # 指定 StorageClass

querier:
  replicas: 2
  maxUnavailable: 1
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  persistence:
    enabled: true
    size: 1Gi
    storageClass: nfs-csi # local-path # 指定 StorageClass

queryFrontend:
  replicas: 2
  maxUnavailable: 1
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

gateway: # nginx容器 -> 路由日志写/读的请求
  nginxConfig:
    httpSnippet: |-
      client_max_body_size 100M;
    serverSnippet: |-
      client_max_body_size 100M;

# Configuration for the ruler
ruler:
  enabled: true
  kind: Deployment
  replicas: 1
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  persistence:
    enabled: true
    size: 1Gi
    storageClass: nfs-csi # local-path # 指定 StorageClass
  # -- Directories containing rules files
  directories:
    tenant_no:
      rules1.txt: |
        groups:
          - name: nginx-rate
            rules:
            - alert: LokiNginxRate
              expr: sum(rate({app="nginx"} |= "error" [1m])) by (job)
                    /
                  sum(rate({app="nginx"}[1m])) by (job)
                    > 0.01
              for: 1m
              labels:
                severity: critical
              annotations:
                summary: loki nginx rate
                description: high request latency